spring.application.name=PP_3_1_1_Spring_Boot
spring.datasource.url=jdbc:mysql://localhost:3306/spring_hiber?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=AGj3HkYRpQ1R

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect